name: Actions

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  run_test:
    name: Run Tests

    strategy:
      matrix:
        unityVersion:
          - 2023.2.7f1
        os:
          - ubuntu-latest
    
    runs-on: ${{ matrix.os }}

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
      
      # Cache
      - uses: actions/cache@v3
        with:
          path: path/to/your/project/Library
          key: Library-MyProjectName-TargetPlatform
          restore-keys: |
            Library-MyProjectName-
            Library-

      # Test
      - name: run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          packageMode: true
          unityVersion: ${{ matrix.unityVersion }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}